[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[client]
showErrorDetails = true
showMenuItems = true

[logger]
level = "warning"

[server]
headless = false
runOnSave = true
maxUploadSize = 200
