[theme]
primaryColor = "#00FF41"
backgroundColor = "#000000"
secondaryBackgroundColor = "#0A0A0A"
textColor = "#FFFFFF"
font = "monospace"

[client]
showErrorDetails = true

[logger]
level = "warning"

[server]
headless = false
runOnSave = true
maxUploadSize = 200
